CREATE TABLE [dbo].[Loan] (
    [STUDENT_ID] NVARCHAR(30),
    [ISBN] NVARCHAR(30),
    [Loan Date] NVARCHAR(30),
	PRIMARY KEY (STUDENT_ID, ISBN),
	FOREIGN KEY (ISBN) REFERENCES Book,
	FOREIGN KEY (STUDENT_ID) REFERENCES Student,
);
