//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public string STUDENT_ID { get; set; }
        public string ISBN { get; set; }
        public string Loan_Date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Student Student { get; set; }
    }
}
